image: node:12.18.1

before_script:
  - npm install

stages:
  - build
  - deploy

compile-project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

production:
  image: ruby:latest
  stage: deploy
  dependencies:
    - compile-project
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master